version: "3.9"
volumes:
  ps: {}
services:
  database:
    build:
      context: ./dockerize_db
      dockerfile: "Dockerfile"
    volumes:
      - ps:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER_NAME}
    ports:
      - "${DB_HOST_PORT}:${DB_DOCKER_PORT}"
    restart: always
  server:
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "${GO_HOST_PORT}:${GO_DOCKER_PORT}"
    restart: always