version: "3.7"
volumes:
  pgdata: {}
services:
  database:
    container_name: database
    image: postgres:15
    build:
      context: ./devenv
      dockerfile: "Dockerfile"
    environment:
      POSTGRES_PASSWORD: default
      POSTGRES_USER: postgres
      POSTGRES_DB: avito
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - 8080:8080